on: push
name: Publish Website
jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: urbandroid-team/jekyll-build-action@6
        env:
          $FTP_USER: ${{ secrets.FTP_USERNAME }}
          $FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          $FTP_SERVER: ${{ secrets.FTP_SERVER }}